### ISSUE TITLE
Where to find PRODUCT_ID and PLACE_ID

### ISSUE THREAD

**Issue by RobbeM1991** [BramB-1952444/colruytPriceChecker#2]
Where can I find the product and place ID for other products?
PRODUCT_ID = "369"
PLACE_ID = "620"

I've been looking around on collect and go and colruyt and can find these 2 links:
https://www.colruyt.be/nl/producten/pils-5-2-vol-5006
https://www.collectandgo.be/colruyt/nl/assortiment/bieren?rootCategoryId=72025#pdp_3074457345616677857

But I don't know how to get the product and place ID for the API?

**Comment by BramB-1952444** [comment]
Go on the product page on the colruyt website and look at the network tab in the developer area. There will be a GET request to the colruyt api. The first number after products/ is the Product_ID and place ID is at the end (You have to set your store on the webpage) I hope this helps

https://apip.colruyt.be/gateway/ictmgmt.emarkecom.cgproductretrsvc.v2/v2/v2/nl/products/369?ts=1686035675736&clientCode=CLP&placeId=620
